### ISSUE TITLE
I am tired XD

### ISSUE THREAD

**Issue by pedrokarim** [Th0rgal/Polymath#4]
I did all the instructions until the run but it doesn't work 😁, I've been trying to do it for 3 hours.

Issue :
![](https://img.ascencia.me/qxeHxOnA.png)

Content `run` file :
![](https://img.ascencia.me/fIOoJnIM.png)

**Comment by Th0rgal** [comment]
Hello!

it loos like you don't have read access to /var/mail/polymath

**Comment by pedrokarim** [comment]
Even with the sudo command it doesn't work.

![](https://img.ascencia.me/ggkBVXjN.png)

But I managed to make it work, I think xD!

I renamed the file `run` --> `run.py`, I removed the `#!/usr/bin/env python` header from the file, and I run the file with `python3 run.py` and there is no error but there is no debug message to tell me if it works so ...

![](https://img.ascencia.me/EfcDeYTG.png)

**Comment by Th0rgal** [comment]
you can try to call it with curl

**Comment by pedrokarim** [comment]
I called the debug route with a curl and everything seems to work fine with this new method.

Thanks to you ! ^^ @Th0rgal
